"""Generates the launcher and store icons of Who's lying? from one geometry definition.

A speech bubble with three "clue" dots, one of them pink: the one who's lying.

Usage (repo root): .venv/bin/python apps/whos-lying/tools/generate_icon.py
"""
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / "app/src/main/res"

TOP, BOTTOM = "#3A2490", "#100E20"
BUBBLE, DOT, LIAR, INK = "#F0EEFF", "#7C5CFF", "#FF4D94", "#100E20"

# 108x108 adaptive viewport, content inside the r=33 safe circle.
BX0, BY0, BX1, BY1, BR = 27.0, 34.0, 81.0, 70.0, 12.0
TAIL = [(38, 68), (34, 80), (50, 69)]
DOTS = [((41, 52), 5.2, DOT), ((54, 52), 5.2, LIAR), ((67, 52), 5.2, DOT)]


def f(v):
    return f"{v:.2f}".rstrip("0").rstrip(".")


def rr(x0, y0, x1, y1, r):
    return (f"M{f(x0 + r)},{f(y0)} H{f(x1 - r)} A{f(r)},{f(r)} 0 0 1 {f(x1)},{f(y0 + r)} V{f(y1 - r)} "
            f"A{f(r)},{f(r)} 0 0 1 {f(x1 - r)},{f(y1)} H{f(x0 + r)} A{f(r)},{f(r)} 0 0 1 {f(x0)},{f(y1 - r)} "
            f"V{f(y0 + r)} A{f(r)},{f(r)} 0 0 1 {f(x0 + r)},{f(y0)} Z")


def poly(points):
    (x, y), *rest = points
    return f"M{f(x)},{f(y)} " + " ".join(f"L{f(a)},{f(b)}" for a, b in rest) + " Z"


def circle(cx, cy, r):
    return f"M{f(cx - r)},{f(cy)} a{f(r)},{f(r)} 0 1 0 {f(2 * r)},0 a{f(r)},{f(r)} 0 1 0 {f(-2 * r)},0 Z"


def path(d, color=None, stroke=None, width=None):
    attrs = f'android:fillColor="{color}"' if color else f'android:strokeColor="{stroke}"\n        android:strokeWidth="{width}"'
    return f'    <path\n        {attrs}\n        android:pathData="{d}" />'


def vector(paths, ns=""):
    return ('<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by tools/generate_icon.py. Do not edit by hand. -->\n'
            f'<vector xmlns:android="http://schemas.android.com/apk/res/android"{ns}\n'
            '    android:width="108dp"\n    android:height="108dp"\n    android:viewportWidth="108"\n'
            '    android:viewportHeight="108">\n' + "\n".join(paths) + "\n</vector>\n")


def write_vectors():
    d, d26, anydpi = RES / "drawable", RES / "drawable-v26", RES / "mipmap-anydpi-v26"
    for p in (d, d26, anydpi):
        p.mkdir(parents=True, exist_ok=True)
    (d26 / "ic_launcher_background.xml").write_text(vector([
        '    <path android:pathData="M0,0h108v108h-108z">\n        <aapt:attr name="android:fillColor">\n'
        '            <gradient\n                android:type="linear"\n                android:startX="54" android:startY="0"\n'
        f'                android:endX="54" android:endY="108"\n                android:startColor="{TOP}"\n'
        f'                android:endColor="{BOTTOM}" />\n        </aapt:attr>\n    </path>'],
        ns='\n    xmlns:aapt="http://schemas.android.com/aapt"'))
    (d / "ic_launcher_foreground.xml").write_text(vector(
        [path(rr(BX0, BY0 + 1.5, BX1, BY1 + 1.5, BR), "#55000000"), path(rr(BX0, BY0, BX1, BY1, BR), BUBBLE), path(poly(TAIL), BUBBLE)]
        + [path(circle(*c, r), col) for c, r, col in DOTS]))
    (d / "ic_launcher_monochrome.xml").write_text(vector(
        [path(rr(BX0 + 1.2, BY0 + 1.2, BX1 - 1.2, BY1 - 1.2, BR - 1.2), stroke="#FF000000", width=2.4), path(poly(TAIL), "#FF000000")]
        + [path(circle(*c, r), "#FF000000") for c, r, _ in DOTS]))
    adaptive = ('<?xml version="1.0" encoding="utf-8"?>\n<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
                '    <background android:drawable="@drawable/ic_launcher_background" />\n'
                '    <foreground android:drawable="@drawable/ic_launcher_foreground" />\n'
                '    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />\n</adaptive-icon>\n')
    (anydpi / "ic_launcher.xml").write_text(adaptive)
    (anydpi / "ic_launcher_round.xml").write_text(adaptive)


def render(size, crop=(0, 108), ss=4):
    s, (lo, hi) = size * ss, crop
    k = s / (hi - lo)

    def P(x, y):
        return ((x - lo) * k, (y - lo) * k)

    grad = Image.new("L", (s, s))
    grad.putdata([int(255 * ((y / k + lo) / 108)) for y in range(s) for _ in range(s)])
    img = Image.composite(Image.new("RGB", (s, s), BOTTOM), Image.new("RGB", (s, s), TOP), grad)
    d = ImageDraw.Draw(img, "RGBA")
    d.rounded_rectangle([P(BX0, BY0 + 1.5), P(BX1, BY1 + 1.5)], radius=BR * k, fill=(0, 0, 0, 85))
    d.rounded_rectangle([P(BX0, BY0), P(BX1, BY1)], radius=BR * k, fill=BUBBLE)
    d.polygon([P(*p) for p in TAIL], fill=BUBBLE)
    for (cx, cy), r, col in DOTS:
        d.ellipse([P(cx - r, cy - r), P(cx + r, cy + r)], fill=col)
    return img.resize((size, size), Image.LANCZOS)


def write_rasters():
    for name, px in {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}.items():
        folder = RES / f"mipmap-{name}"
        folder.mkdir(parents=True, exist_ok=True)
        icon = render(px, crop=(16, 92))
        for shape, filename in (("square", "ic_launcher.png"), ("circle", "ic_launcher_round.png")):
            mask = Image.new("L", (px * 4, px * 4), 0)
            draw = ImageDraw.Draw(mask)
            if shape == "square":
                draw.rounded_rectangle([0, 0, px * 4 - 1, px * 4 - 1], radius=px * 4 * 0.2, fill=255)
            else:
                draw.ellipse([0, 0, px * 4 - 1, px * 4 - 1], fill=255)
            out = icon.convert("RGBA")
            out.putalpha(mask.resize((px, px), Image.LANCZOS))
            out.save(folder / filename, optimize=True)
    (ROOT / "store").mkdir(exist_ok=True)
    render(512, crop=(18, 90)).save(ROOT / "store/play-icon-512.png", optimize=True)


if __name__ == "__main__":
    write_vectors()
    write_rasters()
    print("Icons generated.")
