"""Generates every launcher/store icon asset of the decision wheel from one geometry definition.

Outputs (paths relative to apps/decision-wheel):
  app/src/main/res/drawable{-v26,}/ic_launcher_{background,foreground,monochrome}.xml  adaptive icon
  app/src/main/res/mipmap-anydpi-v26/ic_launcher{,_round}.xml
  app/src/main/res/mipmap-*/ic_launcher{,_round}.png                             legacy icons (API 23-25)
  store/play-icon-512.png                                                        Play Store icon

Usage (repo root): .venv/bin/python apps/decision-wheel/tools/generate_icon.py
"""
import math
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / "app/src/main/res"

NIGHT_TOP, NIGHT_BOTTOM = "#2E2747", "#1F1B2E"
CREAM, NIGHT = "#F7F3EE", "#1F1B2E"
SEGMENTS = ["#FF6B6B", "#FFB347", "#FFD93D", "#4ECDC4", "#6C8EF5", "#C792EA"]

# Geometry in the 108x108 adaptive viewport (safe zone: radius 33 around the centre).
CX, CY, R = 54.0, 57.0, 27.0
GAP = 1.4                       # night-coloured gap between slices
HUB_OUT, HUB_IN = 6.5, 4.0
POINTER = [(54, 36.5), (48.5, 26.5), (59.5, 26.5)]   # tip touches the wheel at the top
ROTATION = -15.0                 # slight tilt: a wheel caught mid-spin


def slice_points(i, n=6, steps=24):
    a0 = math.radians(ROTATION - 90 + i * 360 / n)
    a1 = math.radians(ROTATION - 90 + (i + 1) * 360 / n)
    pts = [(CX, CY)]
    for s in range(steps + 1):
        a = a0 + (a1 - a0) * s / steps
        pts.append((CX + R * math.cos(a), CY + R * math.sin(a)))
    return pts


def f(v):
    return f"{v:.2f}".rstrip("0").rstrip(".")


def poly_path(points):
    head, *rest = points
    return f"M{f(head[0])},{f(head[1])} " + " ".join(f"L{f(x)},{f(y)}" for x, y in rest) + " Z"


def circle_path(cx, cy, r):
    return f"M{f(cx - r)},{f(cy)} a{f(r)},{f(r)} 0 1 0 {f(2 * r)},0 a{f(r)},{f(r)} 0 1 0 {f(-2 * r)},0 Z"


def fill(d, color):
    return f'    <path\n        android:fillColor="{color}"\n        android:pathData="{d}" />'


def stroke(d, color, width):
    return (f'    <path\n        android:strokeColor="{color}"\n        android:strokeWidth="{width}"\n'
            f'        android:strokeLineCap="round"\n        android:pathData="{d}" />')


def vector(paths, extra_ns=""):
    body = "\n".join(paths)
    return (f'<?xml version="1.0" encoding="utf-8"?>\n'
            f'<!-- Generated by tools/generate_icon.py. Do not edit by hand. -->\n'
            f'<vector xmlns:android="http://schemas.android.com/apk/res/android"{extra_ns}\n'
            f'    android:width="108dp"\n    android:height="108dp"\n'
            f'    android:viewportWidth="108"\n    android:viewportHeight="108">\n{body}\n</vector>\n')


def spokes():
    lines = []
    for i in range(6):
        a = math.radians(ROTATION - 90 + i * 60)
        lines.append(f"M{f(CX)},{f(CY)} L{f(CX + R * math.cos(a))},{f(CY + R * math.sin(a))}")
    return " ".join(lines)


def write_vectors():
    drawable, drawable_v26 = RES / "drawable", RES / "drawable-v26"
    drawable.mkdir(parents=True, exist_ok=True)
    drawable_v26.mkdir(parents=True, exist_ok=True)

    background = vector([
        '    <path android:pathData="M0,0h108v108h-108z">\n'
        '        <aapt:attr name="android:fillColor">\n'
        '            <gradient\n'
        '                android:type="linear"\n'
        '                android:startX="54" android:startY="0"\n'
        '                android:endX="54" android:endY="108"\n'
        f'                android:startColor="{NIGHT_TOP}"\n'
        f'                android:endColor="{NIGHT_BOTTOM}" />\n'
        '        </aapt:attr>\n'
        '    </path>'
    ], extra_ns='\n    xmlns:aapt="http://schemas.android.com/aapt"')
    (drawable_v26 / "ic_launcher_background.xml").write_text(background)

    foreground = vector(
        [fill(circle_path(CX, CY, R + 2.2), CREAM)]
        + [fill(poly_path(slice_points(i)), c) for i, c in enumerate(SEGMENTS)]
        + [stroke(spokes(), NIGHT, GAP),
           fill(circle_path(CX, CY, HUB_OUT), NIGHT),
           fill(circle_path(CX, CY, HUB_IN), CREAM),
           fill(poly_path(POINTER), CREAM),
           stroke(poly_path(POINTER), NIGHT, 1.2)]
    )
    (drawable / "ic_launcher_foreground.xml").write_text(foreground)

    monochrome = vector([
        stroke(circle_path(CX, CY, R), "#FF000000", 3),
        stroke(spokes(), "#FF000000", 2.4),
        fill(circle_path(CX, CY, HUB_OUT), "#FF000000"),
        fill(poly_path(POINTER), "#FF000000"),
    ])
    (drawable / "ic_launcher_monochrome.xml").write_text(monochrome)

    adaptive = ('<?xml version="1.0" encoding="utf-8"?>\n'
                '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
                '    <background android:drawable="@drawable/ic_launcher_background" />\n'
                '    <foreground android:drawable="@drawable/ic_launcher_foreground" />\n'
                '    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />\n'
                '</adaptive-icon>\n')
    anydpi = RES / "mipmap-anydpi-v26"
    anydpi.mkdir(parents=True, exist_ok=True)
    (anydpi / "ic_launcher.xml").write_text(adaptive)
    (anydpi / "ic_launcher_round.xml").write_text(adaptive)


def render(size, crop=(0, 108), supersample=4):
    s = size * supersample
    lo, hi = crop
    k = s / (hi - lo)

    def P(x, y):
        return ((x - lo) * k, (y - lo) * k)

    grad = Image.new("L", (s, s))
    grad.putdata([int(255 * ((y / k + lo) / 108)) for y in range(s) for _ in range(s)])
    img = Image.composite(Image.new("RGB", (s, s), NIGHT_BOTTOM), Image.new("RGB", (s, s), NIGHT_TOP), grad)
    d = ImageDraw.Draw(img)
    rr = (R + 2.2) * k
    cx, cy = P(CX, CY)
    d.ellipse([cx - rr, cy - rr, cx + rr, cy + rr], fill=CREAM)
    for i, c in enumerate(SEGMENTS):
        d.polygon([P(*p) for p in slice_points(i)], fill=c)
    for i in range(6):
        a = math.radians(ROTATION - 90 + i * 60)
        d.line([P(CX, CY), P(CX + R * math.cos(a), CY + R * math.sin(a))], fill=NIGHT, width=max(1, int(GAP * k)))
    for r, c in ((HUB_OUT, NIGHT), (HUB_IN, CREAM)):
        d.ellipse([cx - r * k, cy - r * k, cx + r * k, cy + r * k], fill=c)
    d.polygon([P(*p) for p in POINTER], fill=CREAM, outline=NIGHT, width=max(1, int(1.2 * k)))
    return img.resize((size, size), Image.LANCZOS)


def write_rasters():
    for name, px in {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}.items():
        folder = RES / f"mipmap-{name}"
        folder.mkdir(parents=True, exist_ok=True)
        icon = render(px, crop=(16, 92))
        for shape, filename in (("square", "ic_launcher.png"), ("circle", "ic_launcher_round.png")):
            mask = Image.new("L", (px * 4, px * 4), 0)
            draw = ImageDraw.Draw(mask)
            if shape == "square":
                draw.rounded_rectangle([0, 0, px * 4 - 1, px * 4 - 1], radius=px * 4 * 0.2, fill=255)
            else:
                draw.ellipse([0, 0, px * 4 - 1, px * 4 - 1], fill=255)
            out = icon.convert("RGBA")
            out.putalpha(mask.resize((px, px), Image.LANCZOS))
            out.save(folder / filename, optimize=True)
    store = ROOT / "store"
    store.mkdir(exist_ok=True)
    render(512, crop=(18, 90)).save(store / "play-icon-512.png", optimize=True)


if __name__ == "__main__":
    write_vectors()
    write_rasters()
    print("Icons generated.")
