"""Generates the launcher and store icons of "¿Qué votáis?" from one geometry definition.

Two result bars, red on top (the winner, with a check) and a shorter blue one, on a light sky
background: a poll at a glance.

Usage (repo root): .venv/bin/python apps/group-polls/tools/generate_icon.py
"""
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / "app/src/main/res"

TOP, BOTTOM = "#DDEBFF", "#B9D3FF"
RED, BLUE, TRACK, WHITE = "#F2384A", "#2D6BFF", "#FFFFFF", "#FFFFFF"

# 108x108 adaptive viewport, content inside the r=33 safe circle.
X0, X1, H, R = 28.0, 80.0, 16.0, 8.0
RED_Y, BLUE_Y = 37.0, 57.0
RED_END, BLUE_END = 74.0, 52.0
CHECK = [(36, 45), (40.5, 49.5), (48, 41)]


def f(v):
    return f"{v:.2f}".rstrip("0").rstrip(".")


def rr(x0, y0, x1, y1, r):
    return (f"M{f(x0 + r)},{f(y0)} H{f(x1 - r)} A{f(r)},{f(r)} 0 0 1 {f(x1)},{f(y0 + r)} V{f(y1 - r)} "
            f"A{f(r)},{f(r)} 0 0 1 {f(x1 - r)},{f(y1)} H{f(x0 + r)} A{f(r)},{f(r)} 0 0 1 {f(x0)},{f(y1 - r)} "
            f"V{f(y0 + r)} A{f(r)},{f(r)} 0 0 1 {f(x0 + r)},{f(y0)} Z")


def fill(d, color):
    return f'    <path\n        android:fillColor="{color}"\n        android:pathData="{d}" />'


def stroke(d, color, width):
    return (f'    <path\n        android:strokeColor="{color}"\n        android:strokeWidth="{width}"\n'
            f'        android:strokeLineCap="round"\n        android:strokeLineJoin="round"\n        android:pathData="{d}" />')


def check_path():
    (x, y), *rest = CHECK
    return f"M{f(x)},{f(y)} " + " ".join(f"L{f(a)},{f(b)}" for a, b in rest)


def bars(color_for):
    return [
        fill(rr(X0, RED_Y, X1, RED_Y + H, R), color_for("track")),
        fill(rr(X0, BLUE_Y, X1, BLUE_Y + H, R), color_for("track")),
        fill(rr(X0, RED_Y, RED_END, RED_Y + H, R), color_for("red")),
        fill(rr(X0, BLUE_Y, BLUE_END, BLUE_Y + H, R), color_for("blue")),
    ]


def vector(paths, ns=""):
    return ('<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by tools/generate_icon.py. Do not edit by hand. -->\n'
            f'<vector xmlns:android="http://schemas.android.com/apk/res/android"{ns}\n'
            '    android:width="108dp"\n    android:height="108dp"\n    android:viewportWidth="108"\n'
            '    android:viewportHeight="108">\n' + "\n".join(paths) + "\n</vector>\n")


def write_vectors():
    d, d26, anydpi = RES / "drawable", RES / "drawable-v26", RES / "mipmap-anydpi-v26"
    for p in (d, d26, anydpi):
        p.mkdir(parents=True, exist_ok=True)
    (d26 / "ic_launcher_background.xml").write_text(vector([
        '    <path android:pathData="M0,0h108v108h-108z">\n        <aapt:attr name="android:fillColor">\n'
        '            <gradient\n                android:type="linear"\n                android:startX="54" android:startY="0"\n'
        f'                android:endX="54" android:endY="108"\n                android:startColor="{TOP}"\n'
        f'                android:endColor="{BOTTOM}" />\n        </aapt:attr>\n    </path>'],
        ns='\n    xmlns:aapt="http://schemas.android.com/aapt"'))
    colours = {"track": TRACK, "red": RED, "blue": BLUE}
    (d / "ic_launcher_foreground.xml").write_text(vector(bars(colours.get) + [stroke(check_path(), WHITE, 3.2)]))
    mono = {"track": "#55000000", "red": "#FF000000", "blue": "#FF000000"}
    (d / "ic_launcher_monochrome.xml").write_text(vector(bars(mono.get)))
    adaptive = ('<?xml version="1.0" encoding="utf-8"?>\n<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
                '    <background android:drawable="@drawable/ic_launcher_background" />\n'
                '    <foreground android:drawable="@drawable/ic_launcher_foreground" />\n'
                '    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />\n</adaptive-icon>\n')
    (anydpi / "ic_launcher.xml").write_text(adaptive)
    (anydpi / "ic_launcher_round.xml").write_text(adaptive)


def render(size, crop=(0, 108), ss=4):
    s, (lo, hi) = size * ss, crop
    k = s / (hi - lo)

    def P(x, y):
        return ((x - lo) * k, (y - lo) * k)

    grad = Image.new("L", (s, s))
    grad.putdata([int(255 * ((y / k + lo) / 108)) for y in range(s) for _ in range(s)])
    img = Image.composite(Image.new("RGB", (s, s), BOTTOM), Image.new("RGB", (s, s), TOP), grad)
    d = ImageDraw.Draw(img, "RGBA")
    for y, end, color in ((RED_Y, X1, TRACK), (BLUE_Y, X1, TRACK), (RED_Y, RED_END, RED), (BLUE_Y, BLUE_END, BLUE)):
        d.rounded_rectangle([P(X0, y), P(end, y + H)], radius=R * k, fill=color)
    d.line([P(*p) for p in CHECK], fill=WHITE, width=int(3.2 * k), joint="curve")
    for p in (CHECK[0], CHECK[-1]):
        cx, cy = P(*p)
        r = 1.6 * k
        d.ellipse([cx - r, cy - r, cx + r, cy + r], fill=WHITE)
    return img.resize((size, size), Image.LANCZOS)


def write_rasters():
    for name, px in {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}.items():
        folder = RES / f"mipmap-{name}"
        folder.mkdir(parents=True, exist_ok=True)
        icon = render(px, crop=(16, 92))
        for shape, filename in (("square", "ic_launcher.png"), ("circle", "ic_launcher_round.png")):
            mask = Image.new("L", (px * 4, px * 4), 0)
            draw = ImageDraw.Draw(mask)
            if shape == "square":
                draw.rounded_rectangle([0, 0, px * 4 - 1, px * 4 - 1], radius=px * 4 * 0.2, fill=255)
            else:
                draw.ellipse([0, 0, px * 4 - 1, px * 4 - 1], fill=255)
            out = icon.convert("RGBA")
            out.putalpha(mask.resize((px, px), Image.LANCZOS))
            out.save(folder / filename, optimize=True)
    (ROOT / "store").mkdir(exist_ok=True)
    render(512, crop=(18, 90)).save(ROOT / "store/play-icon-512.png", optimize=True)


if __name__ == "__main__":
    write_vectors()
    write_rasters()
    print("Icons generated.")
