"""Builds the Google Play listing graphics of What do you vote? from raw app screenshots.

Inputs:
  store/raw/<locale>/NN-name.png       raw 1080x2424 emulator screenshots (adb exec-out screencap -p)
  store/play-icon-512.png              generated by tools/generate_icon.py
Outputs (fastlane supply layout, next to the listing texts):
  store/metadata/android/<locale>/images/phoneScreenshots/NN.png   1080x1920 framed screenshots
  store/metadata/android/<locale>/images/featureGraphic.png        1024x500 feature graphic
  store/metadata/android/<locale>/images/icon.png                  512x512 store icon

Usage: python3 tools/generate_store_assets.py   (needs Pillow)
"""
import random
import shutil
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter, ImageFont

ROOT = Path(__file__).resolve().parent.parent
STORE = ROOT / "store"
FONT = "/System/Library/Fonts/Avenir Next.ttc"
BOLD, DEMI, MEDIUM, HEAVY = 0, 2, 5, 8

# The app's light palette: sky background, red against blue.
NIGHT_TOP, NIGHT = (221, 235, 255), (243, 246, 251)
GOLD, SNOW = (45, 107, 255), (27, 36, 51)
ACCENTS = [(242, 56, 74), (45, 107, 255), (61, 183, 255)]

LOCALES = {
    "en-US": {
        "title": "What do you vote? Group polls",
        "tagline": "Private by link · Public feed · No ads",
        "headlines": {
            "01-feed": ("Red or blue?", "Ask everyone"),
            "02-vote": ("Tap your half.", "That's your vote"),
            "03-predict": ("Guess what", "most people pick"),
            "04-result": ("See where", "everyone stands"),
            "05-private": ("Private polls:", "see who voted what"),
            "06-create": ("Ask your friends", "with one link"),
        },
    },
    "es-ES": {
        "title": "¿Qué votáis? Sondeos",
        "tagline": "Privadas por enlace · Públicas · Sin anuncios",
        "headlines": {
            "01-feed": ("¿Rojo o azul?", "Pregunta a todos"),
            "02-vote": ("Toca tu mitad.", "Ese es tu voto"),
            "03-predict": ("Adivina qué", "votará la mayoría"),
            "04-result": ("Mira qué opina", "todo el mundo"),
            "05-private": ("Privadas:", "quién ha votado qué"),
            "06-create": ("Pregunta a tus amigos", "con un enlace"),
        },
    },
}


def font(size, face):
    return ImageFont.truetype(FONT, size, index=face)


def background(w, h, seed=7):
    """Night gradient with a few soft blurred accent glows (the app's palette)."""
    img = Image.new("RGB", (w, h))
    px = img.load()
    for y in range(h):
        t = y / (h - 1)
        c = tuple(int(NIGHT_TOP[i] * (1 - t) + NIGHT[i] * t) for i in range(3))
        for x in range(w):
            px[x, y] = c
    glow = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    d = ImageDraw.Draw(glow)
    rng = random.Random(seed)
    for _ in range(7):
        r = rng.uniform(0.08, 0.2) * max(w, h)
        x, y = rng.uniform(0, w), rng.uniform(0, h)
        d.ellipse([x - r, y - r, x + r, y + r], fill=rng.choice(ACCENTS) + (38,))
    glow = glow.filter(ImageFilter.GaussianBlur(max(w, h) * 0.06))
    img.paste(glow, (0, 0), glow)
    return img


def centered_text(draw, text, y, size, face, fill, width):
    f = font(size, face)
    while draw.textlength(text, font=f) > width * 0.9 and size > 20:
        size -= 2
        f = font(size, face)
    x = (width - draw.textlength(text, font=f)) / 2
    draw.text((x, y), text, font=f, fill=fill)
    return y + size * 1.18


def rounded(img, radius):
    mask = Image.new("L", img.size, 0)
    ImageDraw.Draw(mask).rounded_rectangle([0, 0, img.width - 1, img.height - 1], radius=radius, fill=255)
    out = img.convert("RGBA")
    out.putalpha(mask)
    return out


def phone_frame(screenshot, height):
    """Scales a raw screenshot and wraps it in a simple dark bezel with a drop shadow."""
    scale = height / screenshot.height
    screen = screenshot.resize((int(screenshot.width * scale), height), Image.LANCZOS)
    bezel = 14
    body = Image.new("RGBA", (screen.width + 2 * bezel, screen.height + 2 * bezel), (18, 18, 22, 255))
    body = rounded(body, 64)
    body.paste(rounded(screen, 52), (bezel, bezel), rounded(screen, 52))
    shadow = Image.new("RGBA", (body.width + 120, body.height + 120), (0, 0, 0, 0))
    ImageDraw.Draw(shadow).rounded_rectangle([60, 70, body.width + 60, body.height + 70], radius=64, fill=(27, 36, 51, 70))
    shadow = shadow.filter(ImageFilter.GaussianBlur(28))
    shadow.paste(body, (60, 60), body)
    return shadow


def screenshot_card(raw_path, headline):
    w, h = 1080, 1920
    img = background(w, h, seed=sum(raw_path.name.encode()))  # stable across runs
    d = ImageDraw.Draw(img)
    y = 110
    y = centered_text(d, headline[0], y, 84, HEAVY, SNOW, w)
    centered_text(d, headline[1], y, 84, HEAVY, GOLD, w)
    phone = phone_frame(Image.open(raw_path).convert("RGB"), 1420)
    img.paste(phone, ((w - phone.width) // 2, h - phone.height + 20), phone)
    return img


def feature_graphic(locale):
    w, h = 1024, 500
    img = background(w, h, seed=11)
    icon = Image.open(STORE / "play-icon-512.png").convert("RGB").resize((240, 240), Image.LANCZOS)
    shadow = Image.new("RGBA", (300, 300), (0, 0, 0, 0))
    ImageDraw.Draw(shadow).rounded_rectangle([30, 38, 270, 278], radius=54, fill=(27, 36, 51, 60))
    shadow = shadow.filter(ImageFilter.GaussianBlur(16))
    img.paste(shadow, (60, 100), shadow)
    img.paste(rounded(icon, 54), (90, 130), rounded(icon, 54))
    d = ImageDraw.Draw(img)
    text_x, text_w = 380, w - 380 - 50
    title = locale["title"]
    size = 64
    f = font(size, HEAVY)
    words = title.split()
    # Wrap the title into at most two lines that fit the text column.
    lines, line = [], ""
    for word in words:
        candidate = f"{line} {word}".strip()
        if d.textlength(candidate, font=f) <= text_w:
            line = candidate
        else:
            lines.append(line)
            line = word
    lines.append(line)
    y = 250 - (len(lines) * size * 1.1 + 56) / 2
    for i, text in enumerate(lines):
        d.text((text_x, y), text, font=f, fill=SNOW if i == 0 else GOLD)
        y += size * 1.1
    tagline_font = font(26, DEMI)
    while d.textlength(locale["tagline"], font=tagline_font) > text_w:
        tagline_font = font(tagline_font.size - 1, DEMI)
    d.text((text_x, y + 16), locale["tagline"], font=tagline_font, fill=(107, 118, 137))
    return img


def main():
    for code, locale in LOCALES.items():
        images = STORE / "metadata" / "android" / code / "images"
        screenshots = images / "phoneScreenshots"
        screenshots.mkdir(parents=True, exist_ok=True)
        raws = sorted((STORE / "raw" / code).glob("*.png"))
        for i, raw in enumerate(raws, start=1):
            headline = locale["headlines"][raw.stem]
            screenshot_card(raw, headline).save(screenshots / f"{i:02d}.png", optimize=True)
        feature_graphic(locale).save(images / "featureGraphic.png", optimize=True)
        shutil.copyfile(STORE / "play-icon-512.png", images / "icon.png")
        print(f"{code}: {len(raws)} screenshots + feature graphic")


if __name__ == "__main__":
    main()
