"""Generates the launcher and store icons of "¿Qué votáis?" from one geometry definition.

A speech bubble split red | blue (the two answers) with a cream question mark, on the same deep
blue night as the tournaments icon: ask your friends, two answers.

Usage (repo root): .venv/bin/python apps/group-polls/tools/generate_icon.py
"""
import math
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / "app/src/main/res"

TOP, BOTTOM = "#1E3A52", "#12202D"
RED, BLUE, CREAM = "#F2384A", "#2D6BFF", "#F4F1EA"

# 108x108 adaptive viewport, content inside the r=33 safe circle.
BX0, BY0, BX1, BY1, BR = 28.0, 30.0, 80.0, 71.0, 9.0   # bubble body
SPLIT = 54.0                                           # red left of it, blue right
TAIL = [(68.0, 69.0), (56.0, 69.0), (70.0, 82.0)]      # on the blue side (the impostor's bubble points left)
Q_CX, Q_CY, Q_R, Q_W = 54.0, 44.0, 6.8, 4.2           # question mark: hook centre, radius, width
Q_FROM, Q_SWEEP = 200.0, 250.0                         # hook from 200 deg, clockwise, ends straight below
Q_STEM = Q_R * 0.35
Q_DOT_Y, Q_DOT_R = Q_CY + Q_R + Q_STEM + Q_W * 1.6, Q_W * 0.62


def f(v):
    return f"{v:.2f}".rstrip("0").rstrip(".")


def rr(x0, y0, x1, y1, r):
    return (f"M{f(x0 + r)},{f(y0)} H{f(x1 - r)} A{f(r)},{f(r)} 0 0 1 {f(x1)},{f(y0 + r)} V{f(y1 - r)} "
            f"A{f(r)},{f(r)} 0 0 1 {f(x1 - r)},{f(y1)} H{f(x0 + r)} A{f(r)},{f(r)} 0 0 1 {f(x0)},{f(y1 - r)} "
            f"V{f(y0 + r)} A{f(r)},{f(r)} 0 0 1 {f(x0 + r)},{f(y0)} Z")


def fill(d, color):
    return f'    <path\n        android:fillColor="{color}"\n        android:pathData="{d}" />'


def stroke(d, color, width):
    return (f'    <path\n        android:strokeColor="{color}"\n        android:strokeWidth="{width}"\n'
            f'        android:strokeLineCap="round"\n        android:strokeLineJoin="round"\n        android:pathData="{d}" />')


def point(angle_deg, r=Q_R):
    a = math.radians(angle_deg)
    return Q_CX + r * math.cos(a), Q_CY + r * math.sin(a)


def half(left):
    """One half of the bubble body, rounded only on its outer corners."""
    x, sweep = (BX0, 0) if left else (BX1, 1)
    inward = BR if left else -BR
    return (f"M{f(SPLIT)},{f(BY0)} H{f(x + inward)} A{f(BR)},{f(BR)} 0 0 {sweep} {f(x)},{f(BY0 + BR)} "
            f"V{f(BY1 - BR)} A{f(BR)},{f(BR)} 0 0 {sweep} {f(x + inward)},{f(BY1)} H{f(SPLIT)} Z")


def tail_path():
    (x, y), *rest = TAIL
    return f"M{f(x)},{f(y)} " + " ".join(f"L{f(a)},{f(b)}" for a, b in rest) + " Z"


def question_path():
    sx, sy = point(Q_FROM)
    ex, ey = point(Q_FROM + Q_SWEEP)
    return f"M{f(sx)},{f(sy)} A{f(Q_R)},{f(Q_R)} 0 1 1 {f(ex)},{f(ey)} V{f(ey + Q_STEM)}"


def dot_path():
    return f"M{f(Q_CX - Q_DOT_R)},{f(Q_DOT_Y)} a{f(Q_DOT_R)},{f(Q_DOT_R)} 0 1 0 {f(2 * Q_DOT_R)},0 a{f(Q_DOT_R)},{f(Q_DOT_R)} 0 1 0 {f(-2 * Q_DOT_R)},0 Z"


def bubble_outline():
    return rr(BX0, BY0, BX1, BY1, BR)


def vector(paths, ns=""):
    return ('<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by tools/generate_icon.py. Do not edit by hand. -->\n'
            f'<vector xmlns:android="http://schemas.android.com/apk/res/android"{ns}\n'
            '    android:width="108dp"\n    android:height="108dp"\n    android:viewportWidth="108"\n'
            '    android:viewportHeight="108">\n' + "\n".join(paths) + "\n</vector>\n")


def write_vectors():
    d, d26, anydpi = RES / "drawable", RES / "drawable-v26", RES / "mipmap-anydpi-v26"
    for p in (d, d26, anydpi):
        p.mkdir(parents=True, exist_ok=True)
    (d26 / "ic_launcher_background.xml").write_text(vector([
        '    <path android:pathData="M0,0h108v108h-108z">\n        <aapt:attr name="android:fillColor">\n'
        '            <gradient\n                android:type="linear"\n                android:startX="54" android:startY="0"\n'
        f'                android:endX="54" android:endY="108"\n                android:startColor="{TOP}"\n'
        f'                android:endColor="{BOTTOM}" />\n        </aapt:attr>\n    </path>'],
        ns='\n    xmlns:aapt="http://schemas.android.com/aapt"'))
    (d / "ic_launcher_foreground.xml").write_text(vector([
        fill(half(left=True), RED), fill(half(left=False), BLUE), fill(tail_path(), BLUE),
        stroke(question_path(), CREAM, Q_W), fill(dot_path(), CREAM),
    ]))
    # Monochrome (themed icons): the bubble's outline and the question mark.
    (d / "ic_launcher_monochrome.xml").write_text(vector([
        stroke(bubble_outline(), "#FF000000", 3.4), fill(tail_path(), "#FF000000"),
        stroke(question_path(), "#FF000000", Q_W), fill(dot_path(), "#FF000000"),
    ]))
    adaptive = ('<?xml version="1.0" encoding="utf-8"?>\n<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
                '    <background android:drawable="@drawable/ic_launcher_background" />\n'
                '    <foreground android:drawable="@drawable/ic_launcher_foreground" />\n'
                '    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />\n</adaptive-icon>\n')
    (anydpi / "ic_launcher.xml").write_text(adaptive)
    (anydpi / "ic_launcher_round.xml").write_text(adaptive)


def render(size, crop=(0, 108), ss=4):
    s, (lo, hi) = size * ss, crop
    k = s / (hi - lo)

    def P(x, y):
        return ((x - lo) * k, (y - lo) * k)

    grad = Image.new("L", (s, s))
    grad.putdata([int(255 * ((y / k + lo) / 108)) for y in range(s) for _ in range(s)])
    img = Image.composite(Image.new("RGB", (s, s), BOTTOM), Image.new("RGB", (s, s), TOP), grad)
    d = ImageDraw.Draw(img, "RGBA")
    body = Image.new("L", (s, s), 0)
    bd = ImageDraw.Draw(body)
    bd.rounded_rectangle([P(BX0, BY0), P(BX1, BY1)], radius=BR * k, fill=255)
    bd.polygon([P(*p) for p in TAIL], fill=255)
    left = Image.new("L", (s, s), 0)
    ImageDraw.Draw(left).rectangle([(0, 0), (P(SPLIT, 0)[0], s)], fill=255)
    zero = Image.new("L", (s, s), 0)
    img.paste(Image.new("RGB", (s, s), RED), (0, 0), Image.composite(body, zero, left))
    img.paste(Image.new("RGB", (s, s), BLUE), (0, 0), Image.composite(zero, body, left))
    d = ImageDraw.Draw(img)
    hook = [point(Q_FROM + Q_SWEEP * i / 48) for i in range(49)]
    hook.append((Q_CX, hook[-1][1] + Q_STEM))
    w = Q_W * k
    d.line([P(*p) for p in hook], fill=CREAM, width=int(w), joint="curve")
    for p in (hook[0], hook[-1]):
        cx, cy = P(*p)
        d.ellipse([cx - w / 2, cy - w / 2, cx + w / 2, cy + w / 2], fill=CREAM)
    cx, cy = P(Q_CX, Q_DOT_Y)
    d.ellipse([cx - Q_DOT_R * k, cy - Q_DOT_R * k, cx + Q_DOT_R * k, cy + Q_DOT_R * k], fill=CREAM)
    return img.resize((size, size), Image.LANCZOS)


def write_rasters():
    for name, px in {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}.items():
        folder = RES / f"mipmap-{name}"
        folder.mkdir(parents=True, exist_ok=True)
        icon = render(px, crop=(16, 92))
        for shape, filename in (("square", "ic_launcher.png"), ("circle", "ic_launcher_round.png")):
            mask = Image.new("L", (px * 4, px * 4), 0)
            draw = ImageDraw.Draw(mask)
            if shape == "square":
                draw.rounded_rectangle([0, 0, px * 4 - 1, px * 4 - 1], radius=px * 4 * 0.2, fill=255)
            else:
                draw.ellipse([0, 0, px * 4 - 1, px * 4 - 1], fill=255)
            out = icon.convert("RGBA")
            out.putalpha(mask.resize((px, px), Image.LANCZOS))
            out.save(folder / filename, optimize=True)
    (ROOT / "store").mkdir(exist_ok=True)
    render(512, crop=(18, 90)).save(ROOT / "store/play-icon-512.png", optimize=True)


if __name__ == "__main__":
    write_vectors()
    write_rasters()
    print("Icons generated.")
