"""Generates every launcher/store icon asset of the tournaments app from one geometry definition.

A gold bracket climbing to a big "1" with a star on top (only one wins).

Outputs (paths relative to apps/tournaments):
  app/src/main/res/drawable{-v26,}/ic_launcher_{background,foreground,monochrome}.xml  adaptive icon
  app/src/main/res/mipmap-anydpi-v26/ic_launcher{,_round}.xml
  app/src/main/res/mipmap-*/ic_launcher{,_round}.png                             legacy icons (API 23-25)
  store/play-icon-512.png                                                        Play Store icon

Usage (repo root): .venv/bin/python apps/tournaments/tools/generate_icon.py
"""
import math
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / "app/src/main/res"

BG_TOP, BG_BOTTOM = "#1E3A52", "#12202D"
CREAM, GOLD = "#F4F1EA", "#FFC83D"

# Geometry in the 108x108 adaptive viewport (safe zone: radius 33 around the centre).
# A gold bracket climbing to a big "1" with a star on top: only one wins.
W = 3.4          # bracket line width
FLOOR = 80.0     # where the bracket's legs end (flat, the rest of the corners are square)
BRACKET = [
    [(35, FLOOR), (35, 71), (47, 71), (47, FLOOR)],
    [(61, FLOOR), (61, 71), (73, 71), (73, FLOOR)],
    [(41, 71), (41, 62.5), (67, 62.5), (67, 71)],
    [(54, 62.5), (54, 58)],
]
ONE = [(51, 36), (57.5, 36), (57.5, 53), (62, 53), (62, 58), (46, 58), (46, 53), (51, 53), (51, 42.5), (47, 44.5), (45.6, 39.6)]
STAR_CENTRE, STAR_R, STAR_r = (54, 26.5), 7.2, 3.1


def star():
    cx, cy = STAR_CENTRE
    return [(cx + (STAR_R if i % 2 == 0 else STAR_r) * math.cos(math.radians(-90 + i * 36)),
             cy + (STAR_R if i % 2 == 0 else STAR_r) * math.sin(math.radians(-90 + i * 36))) for i in range(10)]


def bracket_rects():
    """Each bracket segment as a rectangle W wide; legs stop flat at FLOOR."""
    rects = []
    for line in BRACKET:
        for (x0, y0), (x1, y1) in zip(line, line[1:]):
            bottom = max(y0, y1) + (0 if FLOOR in (y0, y1) else W / 2)
            rects.append([(min(x0, x1) - W / 2, min(y0, y1) - W / 2), (max(x0, x1) + W / 2, min(y0, y1) - W / 2),
                          (max(x0, x1) + W / 2, bottom), (min(x0, x1) - W / 2, bottom)])
    return rects


# The drawing above spans y 19-80; shrink it a little and centre it so the star clears round masks.
SCALE, MID_Y = 0.92, 49.7


def fit(points):
    return [(54 + (x - 54) * SCALE, 54 + (y - MID_Y) * SCALE) for x, y in points]


def shapes():
    """(polygon, colour) in drawing order, in viewport coordinates."""
    return [(fit(r), GOLD) for r in bracket_rects()] + [(fit(ONE), CREAM), (fit(star()), GOLD)]


def f(v):
    return f"{v:.2f}".rstrip("0").rstrip(".")


def poly_path(points):
    head, *rest = points
    return f"M{f(head[0])},{f(head[1])} " + " ".join(f"L{f(x)},{f(y)}" for x, y in rest) + " Z"


def fill(d, color):
    return f'    <path\n        android:fillColor="{color}"\n        android:pathData="{d}" />'


def vector(paths, extra_ns=""):
    body = "\n".join(paths)
    return (f'<?xml version="1.0" encoding="utf-8"?>\n'
            f'<!-- Generated by tools/generate_icon.py. Do not edit by hand. -->\n'
            f'<vector xmlns:android="http://schemas.android.com/apk/res/android"{extra_ns}\n'
            f'    android:width="108dp"\n    android:height="108dp"\n'
            f'    android:viewportWidth="108"\n    android:viewportHeight="108">\n{body}\n</vector>\n')


def write_vectors():
    drawable, drawable_v26 = RES / "drawable", RES / "drawable-v26"
    drawable.mkdir(parents=True, exist_ok=True)
    drawable_v26.mkdir(parents=True, exist_ok=True)

    background = vector([
        '    <path android:pathData="M0,0h108v108h-108z">\n'
        '        <aapt:attr name="android:fillColor">\n'
        '            <gradient\n'
        '                android:type="linear"\n'
        '                android:startX="54" android:startY="0"\n'
        '                android:endX="54" android:endY="108"\n'
        f'                android:startColor="{BG_TOP}"\n'
        f'                android:endColor="{BG_BOTTOM}" />\n'
        '        </aapt:attr>\n'
        '    </path>'
    ], extra_ns='\n    xmlns:aapt="http://schemas.android.com/aapt"')
    (drawable_v26 / "ic_launcher_background.xml").write_text(background)

    foreground = vector([fill(poly_path(points), colour) for points, colour in shapes()])
    (drawable / "ic_launcher_foreground.xml").write_text(foreground)

    monochrome = vector([fill(poly_path(points), "#FF000000") for points, _ in shapes()])
    (drawable / "ic_launcher_monochrome.xml").write_text(monochrome)

    adaptive = ('<?xml version="1.0" encoding="utf-8"?>\n'
                '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
                '    <background android:drawable="@drawable/ic_launcher_background" />\n'
                '    <foreground android:drawable="@drawable/ic_launcher_foreground" />\n'
                '    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />\n'
                '</adaptive-icon>\n')
    anydpi = RES / "mipmap-anydpi-v26"
    anydpi.mkdir(parents=True, exist_ok=True)
    (anydpi / "ic_launcher.xml").write_text(adaptive)
    (anydpi / "ic_launcher_round.xml").write_text(adaptive)


def render(size, crop=(0, 108), supersample=4):
    s = size * supersample
    lo, hi = crop
    k = s / (hi - lo)

    def P(x, y):
        return ((x - lo) * k, (y - lo) * k)

    grad = Image.new("L", (s, s))
    grad.putdata([int(255 * ((y / k + lo) / 108)) for y in range(s) for _ in range(s)])
    img = Image.composite(Image.new("RGB", (s, s), BG_BOTTOM), Image.new("RGB", (s, s), BG_TOP), grad)
    d = ImageDraw.Draw(img)
    for points, colour in shapes():
        d.polygon([P(*p) for p in points], fill=colour)
    return img.resize((size, size), Image.LANCZOS)


def write_rasters():
    for name, px in {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}.items():
        folder = RES / f"mipmap-{name}"
        folder.mkdir(parents=True, exist_ok=True)
        icon = render(px, crop=(16, 92))
        for shape, filename in (("square", "ic_launcher.png"), ("circle", "ic_launcher_round.png")):
            mask = Image.new("L", (px * 4, px * 4), 0)
            draw = ImageDraw.Draw(mask)
            if shape == "square":
                draw.rounded_rectangle([0, 0, px * 4 - 1, px * 4 - 1], radius=px * 4 * 0.2, fill=255)
            else:
                draw.ellipse([0, 0, px * 4 - 1, px * 4 - 1], fill=255)
            out = icon.convert("RGBA")
            out.putalpha(mask.resize((px, px), Image.LANCZOS))
            out.save(folder / filename, optimize=True)
    store = ROOT / "store"
    store.mkdir(exist_ok=True)
    render(512, crop=(18, 90)).save(store / "play-icon-512.png", optimize=True)


if __name__ == "__main__":
    write_vectors()
    write_rasters()
    print("Icons generated.")
