"""Shared part of every app's tools/generate_icon.py: file layout, vector XML, rasters.

An app only defines its geometry: the foreground and monochrome layers as vector path elements
and a `draw(img, P, k)` that paints the same picture with Pillow. `write_icon` then writes

  app/src/main/res/drawable-v26/ic_launcher_background.xml    gradient background (API 26+)
  app/src/main/res/drawable/ic_launcher_{foreground,monochrome}.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher{,_round}.xml adaptive icon
  app/src/main/res/mipmap-*/ic_launcher{,_round}.png          legacy icons (API 23-25)
  store/play-icon-512.png                                     Play Store icon

Coordinates are in the 108x108 adaptive viewport (safe zone: circle of radius 33 at the centre).
"""
from pathlib import Path

from PIL import Image, ImageDraw

DENSITIES = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}
LEGACY_CROP = (16, 92)   # legacy icons show a bit more than the adaptive mask
STORE_CROP = (18, 90)    # what Play shows of the adaptive icon
AAPT_NS = '\n    xmlns:aapt="http://schemas.android.com/aapt"'
ADAPTIVE = ('<?xml version="1.0" encoding="utf-8"?>\n'
            '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
            '    <background android:drawable="@drawable/ic_launcher_background" />\n'
            '    <foreground android:drawable="@drawable/ic_launcher_foreground" />\n'
            '    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />\n'
            '</adaptive-icon>\n')


def f(v):
    """Number for path data: 2 decimals, no trailing zeros."""
    return f"{v:.2f}".rstrip("0").rstrip(".")


def vector(paths, extra_ns=""):
    body = "\n".join(paths)
    return (f'<?xml version="1.0" encoding="utf-8"?>\n'
            f'<!-- Generated by tools/generate_icon.py. Do not edit by hand. -->\n'
            f'<vector xmlns:android="http://schemas.android.com/apk/res/android"{extra_ns}\n'
            f'    android:width="108dp"\n    android:height="108dp"\n'
            f'    android:viewportWidth="108"\n    android:viewportHeight="108">\n{body}\n</vector>\n')


def fill(d, color):
    return f'    <path\n        android:fillColor="{color}"\n        android:pathData="{d}" />'


def poly_path(points, close=True):
    (x, y), *rest = points
    return f"M{f(x)},{f(y)} " + " ".join(f"L{f(a)},{f(b)}" for a, b in rest) + (" Z" if close else "")


def circle_path(cx, cy, r):
    return f"M{f(cx - r)},{f(cy)} a{f(r)},{f(r)} 0 1 0 {f(2 * r)},0 a{f(r)},{f(r)} 0 1 0 {f(-2 * r)},0 Z"


def background(top, bottom, diagonal=False):
    """Linear gradient filling the viewport: top to bottom, or top-left to bottom-right."""
    end = 'android:endX="108" android:endY="108"' if diagonal else 'android:endX="54" android:endY="108"'
    start = 'android:startX="0" android:startY="0"' if diagonal else 'android:startX="54" android:startY="0"'
    return vector([
        '    <path android:pathData="M0,0h108v108h-108z">\n'
        '        <aapt:attr name="android:fillColor">\n'
        '            <gradient\n'
        '                android:type="linear"\n'
        f'                {start}\n'
        f'                {end}\n'
        f'                android:startColor="{top}"\n'
        f'                android:endColor="{bottom}" />\n'
        '        </aapt:attr>\n'
        '    </path>'
    ], extra_ns=AAPT_NS)


def canvas(size, crop, top, bottom, diagonal=False, supersample=4):
    """Supersampled image with the background gradient, plus P(x, y) → pixels and the scale k."""
    s = size * supersample
    lo, hi = crop
    k = s / (hi - lo)

    def P(x, y):
        return ((x - lo) * k, (y - lo) * k)

    grad = Image.new("L", (s, s))
    if diagonal:
        grad.putdata([int(255 * ((x + y) / k + 2 * lo) / 216) for y in range(s) for x in range(s)])
    else:
        grad.putdata([int(255 * ((y / k + lo) / 108)) for y in range(s) for _ in range(s)])
    img = Image.composite(Image.new("RGB", (s, s), bottom), Image.new("RGB", (s, s), top), grad)
    return img, P, k


def write_icon(root: Path, top, bottom, foreground, monochrome, draw, diagonal=False):
    """Writes every icon file of the app at `root` (apps/<app>). `foreground`/`monochrome` are
    lists of vector path elements; `draw(img, P, k)` paints the foreground on a canvas."""
    res = root / "app/src/main/res"
    drawable, drawable_v26, anydpi = res / "drawable", res / "drawable-v26", res / "mipmap-anydpi-v26"
    for folder in (drawable, drawable_v26, anydpi):
        folder.mkdir(parents=True, exist_ok=True)
    # The gradient attributes need API 24+; the background is only used by the adaptive icon (API 26+).
    (drawable_v26 / "ic_launcher_background.xml").write_text(background(top, bottom, diagonal))
    (drawable / "ic_launcher_foreground.xml").write_text(vector(foreground))
    (drawable / "ic_launcher_monochrome.xml").write_text(vector(monochrome))
    (anydpi / "ic_launcher.xml").write_text(ADAPTIVE)
    (anydpi / "ic_launcher_round.xml").write_text(ADAPTIVE)

    def render(size, crop):
        img, P, k = canvas(size, crop, top, bottom, diagonal)
        draw(img, P, k)
        return img.resize((size, size), Image.LANCZOS)

    for name, px in DENSITIES.items():
        folder = res / f"mipmap-{name}"
        folder.mkdir(parents=True, exist_ok=True)
        icon = render(px, LEGACY_CROP)
        for shape, filename in (("square", "ic_launcher.png"), ("circle", "ic_launcher_round.png")):
            mask = Image.new("L", (px * 4, px * 4), 0)
            mask_draw = ImageDraw.Draw(mask)
            if shape == "square":
                mask_draw.rounded_rectangle([0, 0, px * 4 - 1, px * 4 - 1], radius=px * 4 * 0.2, fill=255)
            else:
                mask_draw.ellipse([0, 0, px * 4 - 1, px * 4 - 1], fill=255)
            out = icon.convert("RGBA")
            out.putalpha(mask.resize((px, px), Image.LANCZOS))
            out.save(folder / filename, optimize=True)
    (root / "store").mkdir(exist_ok=True)
    render(512, STORE_CROP).save(root / "store/play-icon-512.png", optimize=True)
    print("Icons generated.")
