"""Google Play listing graphics shared by every app, from raw emulator screenshots.

Each app keeps a small tools/generate_store_assets.py with its colours (Style) and headlines and
calls build(). Inputs, per app:
  store/raw/<locale>/NN-name.png       raw 1080x2424 emulator screenshots
  store/play-icon-512.png              generated by tools/generate_icon.py
Outputs (fastlane supply layout, next to the listing texts):
  store/metadata/android/<locale>/images/phoneScreenshots/NN.png   1080x1920 framed screenshots
  store/metadata/android/<locale>/images/featureGraphic.png        1024x500 feature graphic
  store/metadata/android/<locale>/images/icon.png                  512x512 store icon

Needs Pillow (scripts/setup-python.sh) and macOS's Avenir Next font.
"""
import random
import shutil
from dataclasses import dataclass, field
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter, ImageFont

FONT = "/System/Library/Fonts/Avenir Next.ttc"
BOLD, DEMI, MEDIUM, HEAVY = 0, 2, 5, 8


@dataclass(frozen=True)
class Style:
    top: tuple            # background gradient, top colour (RGB)
    bottom: tuple         # background gradient, bottom colour
    headline: tuple       # first headline line and app name
    highlight: tuple      # second headline line
    tagline: tuple        # feature graphic tagline
    accents: list = field(default_factory=list)  # glow colours ("glow" decoration)
    decoration: str = "glow"                      # "glow" or "snow"
    feature_seed: int = 11


def font(size, face):
    return ImageFont.truetype(FONT, size, index=face)


def background(style, w, h, seed=7):
    """The app's vertical gradient with soft blurred accent glows, or falling snow."""
    img = Image.new("RGB", (w, h))
    px = img.load()
    for y in range(h):
        t = y / (h - 1)
        c = tuple(int(style.top[i] * (1 - t) + style.bottom[i] * t) for i in range(3))
        for x in range(w):
            px[x, y] = c
    layer = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    d = ImageDraw.Draw(layer)
    rng = random.Random(seed)
    if style.decoration == "snow":
        for _ in range(int(w * h / 9000)):
            r = rng.uniform(1.5, 4.5) * w / 1080
            x, y = rng.uniform(0, w), rng.uniform(0, h)
            d.ellipse([x - r, y - r, x + r, y + r], fill=(255, 255, 255, int(60 + r * 25)))
    else:
        for _ in range(7):
            r = rng.uniform(0.08, 0.2) * max(w, h)
            x, y = rng.uniform(0, w), rng.uniform(0, h)
            d.ellipse([x - r, y - r, x + r, y + r], fill=rng.choice(style.accents) + (38,))
        layer = layer.filter(ImageFilter.GaussianBlur(max(w, h) * 0.06))
    img.paste(layer, (0, 0), layer)
    return img


def centered_text(draw, text, y, size, face, fill, width):
    f = font(size, face)
    while draw.textlength(text, font=f) > width * 0.9 and size > 20:
        size -= 2
        f = font(size, face)
    x = (width - draw.textlength(text, font=f)) / 2
    draw.text((x, y), text, font=f, fill=fill)
    return y + size * 1.18


def rounded(img, radius):
    mask = Image.new("L", img.size, 0)
    ImageDraw.Draw(mask).rounded_rectangle([0, 0, img.width - 1, img.height - 1], radius=radius, fill=255)
    out = img.convert("RGBA")
    out.putalpha(mask)
    return out


def phone_frame(screenshot, height):
    """Scales a raw screenshot and wraps it in a simple dark bezel with a drop shadow."""
    scale = height / screenshot.height
    screen = screenshot.resize((int(screenshot.width * scale), height), Image.LANCZOS)
    bezel = 14
    body = Image.new("RGBA", (screen.width + 2 * bezel, screen.height + 2 * bezel), (18, 18, 22, 255))
    body = rounded(body, 64)
    body.paste(rounded(screen, 52), (bezel, bezel), rounded(screen, 52))
    shadow = Image.new("RGBA", (body.width + 120, body.height + 120), (0, 0, 0, 0))
    ImageDraw.Draw(shadow).rounded_rectangle([60, 70, body.width + 60, body.height + 70], radius=64, fill=(0, 0, 0, 150))
    shadow = shadow.filter(ImageFilter.GaussianBlur(28))
    shadow.paste(body, (60, 60), body)
    return shadow


def screenshot_card(style, raw_path, headline):
    w, h = 1080, 1920
    img = background(style, w, h, seed=sum(raw_path.name.encode()))  # stable across runs
    d = ImageDraw.Draw(img)
    y = 110
    y = centered_text(d, headline[0], y, 84, HEAVY, style.headline, w)
    centered_text(d, headline[1], y, 84, HEAVY, style.highlight, w)
    phone = phone_frame(Image.open(raw_path).convert("RGB"), 1420)
    img.paste(phone, ((w - phone.width) // 2, h - phone.height + 20), phone)
    return img


def feature_graphic(style, store, locale):
    w, h = 1024, 500
    img = background(style, w, h, seed=style.feature_seed)
    icon = Image.open(store / "play-icon-512.png").convert("RGB").resize((240, 240), Image.LANCZOS)
    shadow = Image.new("RGBA", (300, 300), (0, 0, 0, 0))
    ImageDraw.Draw(shadow).rounded_rectangle([30, 38, 270, 278], radius=54, fill=(0, 0, 0, 140))
    shadow = shadow.filter(ImageFilter.GaussianBlur(16))
    img.paste(shadow, (60, 100), shadow)
    img.paste(rounded(icon, 54), (90, 130), rounded(icon, 54))
    d = ImageDraw.Draw(img)
    text_x, text_w = 380, w - 380 - 50
    title = locale["title"]
    size = 64
    f = font(size, HEAVY)
    if "? " in title:
        # "¿Question? What it is": the question on top, the keyword part in the highlight colour.
        question, rest = title.split("? ", 1)
        lines = [question + "?", rest]
        while max(d.textlength(t, font=f) for t in lines) > text_w and size > 40:
            size -= 2
            f = font(size, HEAVY)
    else:
        # Wrap the title into at most two lines that fit the text column.
        lines, line = [], ""
        for word in title.split():
            candidate = f"{line} {word}".strip()
            if d.textlength(candidate, font=f) <= text_w:
                line = candidate
            else:
                lines.append(line)
                line = word
        lines.append(line)
    y = 250 - (len(lines) * size * 1.1 + 56) / 2
    for i, text in enumerate(lines):
        d.text((text_x, y), text, font=f, fill=style.headline if i == 0 else style.highlight)
        y += size * 1.1
    tagline_font = font(26, DEMI)
    while d.textlength(locale["tagline"], font=tagline_font) > text_w:
        tagline_font = font(tagline_font.size - 1, DEMI)
    d.text((text_x, y + 16), locale["tagline"], font=tagline_font, fill=style.tagline)
    return img


def build(app_dir, style, locales):
    """Writes the listing graphics of the app in app_dir (see the module docstring)."""
    store = Path(app_dir) / "store"
    for code, locale in locales.items():
        images = store / "metadata" / "android" / code / "images"
        screenshots = images / "phoneScreenshots"
        screenshots.mkdir(parents=True, exist_ok=True)
        raws = sorted((store / "raw" / code).glob("*.png"))
        for i, raw in enumerate(raws, start=1):
            headline = locale["headlines"][raw.stem]
            screenshot_card(style, raw, headline).save(screenshots / f"{i:02d}.png", optimize=True)
        feature_graphic(style, store, locale).save(images / "featureGraphic.png", optimize=True)
        shutil.copyfile(store / "play-icon-512.png", images / "icon.png")
        print(f"{code}: {len(raws)} screenshots + feature graphic")
