"""Generates every launcher/store icon asset from a single geometry definition.

Outputs (paths relative to apps/christmas-countdown):
  app/src/main/res/drawable{-v26,}/ic_launcher_{background,foreground,monochrome}.xml  adaptive icon layers
  app/src/main/res/mipmap-anydpi-v26/ic_launcher{,_round}.xml                    adaptive icon
  app/src/main/res/mipmap-*/ic_launcher{,_round}.png                             legacy icons (API 23-25)
  store/play-icon-512.png                                                        Play Store listing icon

Usage: python3 tools/generate_icon.py   (needs Pillow)
"""
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / "app/src/main/res"

# Palette
BG_START, BG_END = "#D7263D", "#7A0F1C"
PAGE, HEADER, RINGS = "#FFF8EE", "#1F7A4D", "#FFC857"
TREE, STAR, TRUNK = "#2A9D5C", "#FFB703", "#8D5524"
BAUBLE_RED, BAUBLE_GOLD = "#E63946", "#FFB703"

# Geometry in the 108x108 adaptive-icon viewport (safe zone: circle of radius 33 at the centre).
PAGE_RECT = (32, 36, 76, 80, 6)
HEADER_RECT = (32, 36, 76, 47, 6)
RING_RECTS = [(41, 31, 45, 40, 2), (63, 31, 67, 40, 2)]
TREE_TRIANGLES = [
    [(54, 54), (47.5, 61), (60.5, 61)],
    [(54, 58.5), (45, 67), (63, 67)],
    [(54, 63.5), (42.5, 73), (65.5, 73)],
]
TRUNK_RECT = (52, 73, 56, 76.5)
STAR_CENTER, STAR_RADIUS = (54, 52), 3.4
BAUBLES = [((51, 64.5), 1.2, BAUBLE_RED), ((57.5, 69.5), 1.2, BAUBLE_RED),
           ((49, 70.5), 1.1, BAUBLE_GOLD), ((56.5, 61), 1.0, BAUBLE_GOLD)]


def star_points(cx, cy, r):
    import math
    pts = []
    for i in range(10):
        rad = r if i % 2 == 0 else r * 0.45
        a = -math.pi / 2 + i * math.pi / 5
        pts.append((cx + rad * math.cos(a), cy + rad * math.sin(a)))
    return pts


# ---------- Vector drawable output ----------

def f(v):
    return f"{v:g}"


def rr_path(x0, y0, x1, y1, r):
    return (f"M{f(x0 + r)},{f(y0)} H{f(x1 - r)} A{f(r)},{f(r)} 0 0 1 {f(x1)},{f(y0 + r)} "
            f"V{f(y1 - r)} A{f(r)},{f(r)} 0 0 1 {f(x1 - r)},{f(y1)} H{f(x0 + r)} "
            f"A{f(r)},{f(r)} 0 0 1 {f(x0)},{f(y1 - r)} V{f(y0 + r)} A{f(r)},{f(r)} 0 0 1 {f(x0 + r)},{f(y0)} Z")


def top_rounded_path(x0, y0, x1, y1, r):
    return (f"M{f(x0)},{f(y1)} V{f(y0 + r)} A{f(r)},{f(r)} 0 0 1 {f(x0 + r)},{f(y0)} "
            f"H{f(x1 - r)} A{f(r)},{f(r)} 0 0 1 {f(x1)},{f(y0 + r)} V{f(y1)} Z")


def poly_path(points):
    head, *rest = points
    return f"M{f(head[0])},{f(head[1])} " + " ".join(f"L{f(x)},{f(y)}" for x, y in rest) + " Z"


def circle_path(cx, cy, r):
    return f"M{f(cx - r)},{f(cy)} a{f(r)},{f(r)} 0 1 0 {f(2 * r)},0 a{f(r)},{f(r)} 0 1 0 {f(-2 * r)},0 Z"


def rect_path(x0, y0, x1, y1):
    return f"M{f(x0)},{f(y0)} H{f(x1)} V{f(y1)} H{f(x0)} Z"


def vector(paths, extra_ns=""):
    body = "\n".join(paths)
    return (f'<?xml version="1.0" encoding="utf-8"?>\n'
            f'<!-- Generated by tools/generate_icon.py. Do not edit by hand. -->\n'
            f'<vector xmlns:android="http://schemas.android.com/apk/res/android"{extra_ns}\n'
            f'    android:width="108dp"\n    android:height="108dp"\n'
            f'    android:viewportWidth="108"\n    android:viewportHeight="108">\n{body}\n</vector>\n')


def fill(d, color):
    return f'    <path\n        android:fillColor="{color}"\n        android:pathData="{d}" />'


def tree_paths(color_tree, color_star, color_trunk, baubles=True):
    out = [fill(poly_path(t), color_tree) for t in TREE_TRIANGLES]
    out.append(fill(rect_path(*TRUNK_RECT), color_trunk))
    out.append(fill(poly_path(star_points(*STAR_CENTER, STAR_RADIUS)), color_star))
    if baubles:
        out += [fill(circle_path(*c, r), col) for c, r, col in BAUBLES]
    return out


def write_vectors():
    drawable = RES / "drawable"
    drawable.mkdir(parents=True, exist_ok=True)
    # The gradient attributes need API 24+; the background is only used by the adaptive icon (API 26+).
    drawable_v26 = RES / "drawable-v26"
    drawable_v26.mkdir(parents=True, exist_ok=True)
    background = vector([
        '    <path android:pathData="M0,0h108v108h-108z">\n'
        '        <aapt:attr name="android:fillColor">\n'
        '            <gradient\n'
        '                android:type="linear"\n'
        '                android:startX="0" android:startY="0"\n'
        '                android:endX="108" android:endY="108"\n'
        f'                android:startColor="{BG_START}"\n'
        f'                android:endColor="{BG_END}" />\n'
        '        </aapt:attr>\n'
        '    </path>'
    ], extra_ns='\n    xmlns:aapt="http://schemas.android.com/aapt"')
    (drawable_v26 / "ic_launcher_background.xml").write_text(background)

    x0, y0, x1, y1, r = PAGE_RECT
    foreground = vector(
        [fill(rr_path(x0, y0 + 1.5, x1, y1 + 1.5, r), "#40000000"),  # soft drop shadow
         fill(rr_path(*PAGE_RECT), PAGE),
         fill(top_rounded_path(*HEADER_RECT), HEADER)]
        + [fill(rr_path(*ring), RINGS) for ring in RING_RECTS]
        + tree_paths(TREE, STAR, TRUNK)
    )
    (drawable / "ic_launcher_foreground.xml").write_text(foreground)

    # Monochrome (themed icons): page outline, solid header and rings, solid tree.
    outline = (f'    <path\n        android:strokeColor="#FF000000"\n        android:strokeWidth="2.4"\n'
               f'        android:pathData="{rr_path(x0 + 1.2, y0 + 1.2, x1 - 1.2, y1 - 1.2, r - 1.2)}" />')
    monochrome = vector(
        [outline, fill(top_rounded_path(*HEADER_RECT), "#FF000000")]
        + [fill(rr_path(*ring), "#FF000000") for ring in RING_RECTS]
        + tree_paths("#FF000000", "#FF000000", "#FF000000", baubles=False)
    )
    (drawable / "ic_launcher_monochrome.xml").write_text(monochrome)

    adaptive = ('<?xml version="1.0" encoding="utf-8"?>\n'
                '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
                '    <background android:drawable="@drawable/ic_launcher_background" />\n'
                '    <foreground android:drawable="@drawable/ic_launcher_foreground" />\n'
                '    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />\n'
                '</adaptive-icon>\n')
    anydpi = RES / "mipmap-anydpi-v26"
    anydpi.mkdir(parents=True, exist_ok=True)
    (anydpi / "ic_launcher.xml").write_text(adaptive)
    (anydpi / "ic_launcher_round.xml").write_text(adaptive)


# ---------- Raster output ----------

def render(size, crop=(0, 108), supersample=4):
    """Renders the full icon (background + foreground) for the viewport window [crop0, crop1]."""
    s = size * supersample
    lo, hi = crop
    k = s / (hi - lo)

    def P(x, y):
        return ((x - lo) * k, (y - lo) * k)

    # Diagonal gradient matching the vector background (top-left -> bottom-right of the full viewport).
    grad = Image.new("L", (s, s))
    grad.putdata([int(255 * ((x + y) / k + 2 * lo) / 216) for y in range(s) for x in range(s)])
    img = Image.composite(Image.new("RGB", (s, s), BG_END), Image.new("RGB", (s, s), BG_START), grad)
    d = ImageDraw.Draw(img, "RGBA")

    def rrect(x0, y0, x1, y1, r, color):
        d.rounded_rectangle([P(x0, y0), P(x1, y1)], radius=r * k, fill=color)

    x0, y0, x1, y1, r = PAGE_RECT
    rrect(x0, y0 + 1.5, x1, y1 + 1.5, r, (0, 0, 0, 64))
    rrect(*PAGE_RECT, PAGE)
    hx0, hy0, hx1, hy1, hr = HEADER_RECT
    rrect(hx0, hy0, hx1, hy1, hr, HEADER)
    d.rectangle([P(hx0, hy0 + hr), P(hx1, hy1)], fill=HEADER)
    for ring in RING_RECTS:
        rrect(*ring, RINGS)
    for t in TREE_TRIANGLES:
        d.polygon([P(*p) for p in t], fill=TREE)
    d.rectangle([P(TRUNK_RECT[0], TRUNK_RECT[1]), P(TRUNK_RECT[2], TRUNK_RECT[3])], fill=TRUNK)
    d.polygon([P(*p) for p in star_points(*STAR_CENTER, STAR_RADIUS)], fill=STAR)
    for (cx, cy), br, col in BAUBLES:
        d.ellipse([P(cx - br, cy - br), P(cx + br, cy + br)], fill=col)
    return img.resize((size, size), Image.LANCZOS)


def write_rasters():
    densities = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}
    for name, px in densities.items():
        folder = RES / f"mipmap-{name}"
        folder.mkdir(parents=True, exist_ok=True)
        icon = render(px, crop=(16, 92))
        square = Image.new("L", (px * 4, px * 4), 0)
        ImageDraw.Draw(square).rounded_rectangle([0, 0, px * 4 - 1, px * 4 - 1], radius=px * 4 * 0.2, fill=255)
        circle = Image.new("L", (px * 4, px * 4), 0)
        ImageDraw.Draw(circle).ellipse([0, 0, px * 4 - 1, px * 4 - 1], fill=255)
        for mask, filename in ((square, "ic_launcher.png"), (circle, "ic_launcher_round.png")):
            out = icon.convert("RGBA")
            out.putalpha(mask.resize((px, px), Image.LANCZOS))
            out.save(folder / filename, optimize=True)

    store = ROOT / "store"
    store.mkdir(exist_ok=True)
    render(512, crop=(18, 90)).save(store / "play-icon-512.png", optimize=True)


if __name__ == "__main__":
    write_vectors()
    write_rasters()
    print("Icons generated.")
